### ISSUE TITLE
Chat is spammed with "gps started" and "destination reached" when doing a quest.

### ISSUE THREAD

**Issue by nuttapillar** [PikaMug/GPS-Quests#9]
![image](https://user-images.githubusercontent.com/22978620/179167404-5b61dab3-3d19-4113-8258-147700c01242.png)
Starting a quest causes "gps started" to continuously applear in chat until the destination is reached. Then it starts spamming  "destination reached".
[quest.txt](https://github.com/PikaMug/GPS-Quests/files/9118562/quest.txt)
I have attaached the data for a quest that causes this issue in my server

**Comment by PikaMug** [comment]
Thanks for the report. Please note that those messages are from GPS (not Quests or GPS-Quests) so all I can do is try to reduce their frequency.

I wasn't able to replicate this using your quest (for which I had to remove the start/finish actions since they weren't included), but looking at your screenshot this appears to be a duplicate of #8 which I wasn't able to replicate either.

Could you kindly reply with the following?:

- Version number of Quests
- Version number of GPS
- Version number of GPS-Quests
- Version number of QuestsBar

**Comment by nuttapillar** [comment]
Quests 4.5.1, Im unsure of GPS version, as I was given a download link when I bought it about a week ago. So pretty recent, GPS Quests 1.8, QuestsBar is 1.6

**Comment by PikaMug** [comment]
Please use _/gpsa info_ to get the GPS version.

**Comment by nuttapillar** [comment]
2.19.22

**Comment by nuttapillar** [comment]
Hello, is there any update? Players on my server are getting annoyed with the message spam. They can't do quests in peace.

**Comment by nuttapillar** [comment]
It only seems to be happening on quests that require the player to go to a given area. The message spams until the player gets there, then it stops. So basically as long as they are in a stage with a required location, it seems.

**Comment by PikaMug** [comment]
I still haven't been able to replicate this. For the time being, consider asking the GPS developer if there's a way to disable those messages.

**Comment by nuttapillar** [comment]
Oh, this might help: It only shows up for non-op/non-admin players it seems. I can't replicate it either as server owner, but when I join with an alt account and start the quest, it shows up.

**Comment by ghost** [comment]
Yeah I have the exact same issue.

**Using:**
- Quests v4.5.3
- QuestsBar v1.7
- QuestsGUI v0.48
- GPSQuests v1.8
- GPS v2.19.23

**The Quest**
```
  custom5:
    name: Q005
    ask-message: Go up on the mountain. Look for the light.
    finish-message: Good job! Here's 200$
    npc-giver-uuid: 1e99c552-091c-4e8f-8ada-aca3ebd6c746
    stages:
      ordered:
        '1':
          locations-to-reach:
          - 5FEM 157.0 103.0 -236.0
          reach-location-radii:
          - 5
          reach-location-names:
          - Up on the mountain
          start-message: Go towards the light on the mountain!
    rewards:
      money: 200
      exp: 250
    planner:
      cooldown: 300
````

**How it looks in chat**
https://i.imgur.com/qJOlLbH.png


**My permissions (given to default group)**
https://i.imgur.com/pmOydMm.png


**Reproducing**

1. Create a quest
2. Set a location block
3. Save and close the quest editor
4. Do the `/questadmin reload`
5. Make sure you're a **normal user**. That your user is de-op'd.
6. This only appears when using a NON-OP user.
7. Take the quest
8. Watch the `GPS Started!` error repeat over and over.


It's very reproducible on my end. It only happens when the user taking the quest is a default / non-OP user.
